### ISSUE TITLE
Incorrect behavior of widening/narrowing `svcvt` instructions

### ISSUE THREAD

**Issue by al42and** [berenger-eu/farm-sve#7]
Hello!

I noticed a discrepancy in the behavior of `svcvt` functions in farm-sve, compared to the ARM spec.

For example, [`svcvt_f64[_f32]_z`](https://developer.arm.com/architectures/instruction-sets/intrinsics/#q=svcvt_):

> Return a vector in which each active element _i_ contains `(float64_t)op[i * 2]`. Set the inactive elements of the result to zero.

However, in farm-sve, it returns `(float64_t)op[i]` (for the first half of the vector):

```cpp
inline svfloat64_t svcvt_f64_f32_z(svbool_t pg, svfloat32_t op) {
  svfloat64_t res;
  for (int idx = 0; idx < core_min(res.Size, op.Size); ++idx) {
    if (pg.vec[idx]) {
      res.vec[idx] = op.vec[idx];
    }
  }
  return res;
}
```

Same applies for other widening conversions.

Narrowing conversions, on the other hand, should "Convert each active element op[i] to {new type}, rounding according to the current rounding mode. Return the converted value in element i * {stride} of the result vector and return zero in {other elements}". But in farm-sve, they fill the first half/quarter contiguously instead.

I can submit a manual fix later, but since "the implementation was generated semi-automatically", perhaps it would be easier to fix the generator?

**Comment by berenger-eu** [comment]
Hello. Thanks for the feedback. The generator was dumb scripts that are not easy to make accurate. So I think one should do it by hand. If you can do it that would be great, otherwise, I will try to do it next month. Thanks.

**Comment by al42and** [comment]
>  If you can do it that would be great, otherwise, I will try to do it next month. Thanks.

I hope to find time this week for this and #6, then. Is there any automated testing suite to run, or is it enough to manually check a few cases?
